version: '3.8'

services:
  arcade-web:
    image: nginx:latest
    container_name: arcade-web
    ports:
      - "80:80"
    volumes:
      - ./arcade-frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web-net
    restart: unless-stopped

  resume-web:
      image: nginx:latest
      container_name: resume-web
      volumes:
        - ./resume-site:/usr/share/nginx/html
      networks:
        - web-net
      restart: unless-stopped

  horror-web:
      image: nginx:latest
      container_name: horror-web
      volumes:
        - ./horror-site:/usr/share/nginx/html
      networks:
        - web-net
      restart: unless-stopped  

  arcade-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: arcade-tunnel
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=TokenTokenTokenTokenTokenTokenTokenTokenTokenTokenTokenTokenTokenTokenTokenTokenTokenTokenTokenToken
    networks:
      - web-net
    restart: unless-stopped

networks:
  web-net:
    driver: bridge
